server:
  address: localhost
  port: 8443
  compression:
    enabled: true
  http2:
    enabled: true

  error:
    whitelabel:
      enabled: false
  ssl:
    enabled: true
    key-alias: localtomcat
    key-store: classpath:ssl/local-tomcat-private.p12
    key-store-type: PKCS12

    key-password: ${ssl-key-password}
    key-store-password: ${ssl-key-store-password}
    trust-store-password: ${ssl-key-store-password}

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test10?characterEncoding=utf8"
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  profiles:
    active: "dev"

  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    generate-ddl: true

    properties:
      hibernate:
        default_batch_fetch_size: 20
        jdbc:
          batch_size: 10
          order_inserts: true
          order_updates: true

    # решает ошибку ClassCastException EntityManagerHolder
    open-in-view: false

  jackson:
    serialization:
      indent-output: true
      write_dates_as_timestamps: false

  flyway:
    enabled: true
    url: "jdbc:mysql://localhost:3306/test10?characterEncoding=utf8"
    user: ${datasource.username}
    password: ${datasource.password}

  boot:
    admin:
      client:
        enabled: true
        url: "https://0.0.0.0:4444"

logging:
  config: "classpath:log4j2.properties"
  level:
    ROOT: INFO
    org:
      springframework.web: DEBUG
      hibernate: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
