server:
  address: localhost
  port: 8443
  compression:
    enabled: true
  http2:
    enabled: true

  error:
    whitelabel:
      enabled: false
  ssl:
    enabled: true
    key-alias: tomcat
    key-store: classpath:ssl/tomcat-private.p12
    key-store-type: PKCS12

    key-password: ${ssl-key-password}
    key-store-password: ${ssl-key-store-password}
    trust-store-password: ${ssl-key-store-password}

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test10?characterEncoding=utf8"
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  profiles:
    active: "dev"

  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    generate-ddl: true

    properties:
      hibernate:
        default_batch_fetch_size: 20
        jdbc:
          batch_size: 10
          order_inserts: true
          order_updates: true

    # решает ошибку ClassCastException EntityManagerHolder
    open-in-view: false

  #    show-sql: true
  #    hibernate:
  #      ddl-auto: "none"
  #      use-new-id-generator-mappings: false
  #
  #    properties:
  #      hibernate:
  #        generate_statistics: true
  #        current_session_context_class: "thread"
  #        jdbc:
  #          batch_size: 10
  #        format_sql: true
  #        connection:
  #          autocommit: false

  jackson:
    serialization:
      indent-output: true
      write_dates_as_timestamps: false

  flyway:
    enabled: true
    url: "jdbc:mysql://localhost:3306/test10?characterEncoding=utf8"
    user: ${datasource.username}
    password: ${datasource.password}
    fly

logging:
  config: "classpath:log4j2.properties"
  level:
    ROOT: INFO
    org:
      springframework.web: DEBUG
      hibernate: INFO
